### ISSUE TITLE
Meshroom on Colab

### ISSUE THREAD

**Issue by RayzedByRobots** [ab3d-studio/colab-notebooks#1]
Hi thanks for uploading the meshroom notebook for Colab and your youtube video as well. 

Questions for you: are the default settings for meshroom being used or did you change any of these?  For instance, with the feature extraction node you can choose normal, high or ultra.

If these are the default settings is there a way to adjust these via the notebook?

Thanks - Ron

**Comment by abnlsn** [comment]
Hi @RayzedByRobots ! I'm glad you found the notebook and video helpful! I explored your question for a while, and I came up with some answers. I haven't extensively tried any of this but here is what I found:
This is kind of the default do it all command that the notebook currently uses: `!./meshroom/Meshroom-2019.1.0/meshroom_photogrammetry --input '/content/dataset_buddha/buddha_mini6' --output '{output_path}'`
If you are looking for this, it is under the Meshing cell.
When we run this, we get a lot of lines of output that show us what step the meshing is on. These lines are actually super helpful. You were wondering about the feature extraction section, which is the second step that meshroom does. Here is it's output:
```
[2/12] FeatureExtraction
 - commandLine: aliceVision_featureExtraction  --input "/tmp/MeshroomCache/CameraInit/cc70b3398009e18fe2b12ed253ffbbb7f8d6092e/cameraInit.sfm" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output "/tmp/MeshroomCache/FeatureExtraction/e40ecc7566a8bb62d73840b840648044eebdc966" --rangeStart 0 --rangeSize 7
 - logFile: /tmp/MeshroomCache/FeatureExtraction/e40ecc7566a8bb62d73840b840648044eebdc966/0.log
 - elapsed time: 0:00:05.426531
```
If we look closely at this output, we find exactly what we need: the command line code with the file we need to execute: `aliceVision_featureExtraction`. I found this file on the machine under `/content/meshroom/Meshroom-2019.1.0/aliceVision/bin/aliceVision_featureMatching` where it seems like all the different steps are located. So this is the command to run for this step. I haven't tested it, but I'm guessing that you can change a bunch of these arguments. I believe that `--describerPreset normal` is what you could change to ultra.
As for actually using this, here is what I think you can do:
Look at the command for each step and make a separate cell for each step with each command and run them in order. For example, to run feature extraction, you would run `!/content/meshroom/Meshroom-2019.1.0/aliceVision/bin/aliceVision_featureMatching --input {input path}  --output {output path} --etc...`. The input path will be the result of the previous step, and the output will be used by the next step. You can then change each of these steps to what you like. Documentation for these steps/nodes is [in the Meshroom manual here](https://meshroom-manual.readthedocs.io/en/latest/node-reference/node-reference.html). I hope this helps. Let me know what you did, maybe make a PR if you figure it out. I would love to see what you come up with!

**Comment by RayzedByRobots** [comment]
@ab3d-studio wow thank you so much for all of the great info! This is really helpful. Some of the models I've run end up running out of memory on my PC and having a way to run them FOR FREE in the cloud is almost too good to be true.  I will try what you suggest and let you know how it goes. R

**Comment by RayzedByRobots** [comment]
@ab3d-studio - When you say "I found this file on the **machine** under /content/meshroom/Meshroom-2019.1.0/aliceVision/bin/aliceVision_featureMatching where it seems like all the different steps are located." What do you mean by the machine? I'm having trouble locating where the different steps are located i.e. featureMatching Thanks

**Comment by abnlsn** [comment]
Hi - sorry I didn't see this until now. I was just talking about the google colab server you are connected to. You can find all the files on this server by the file browser tab on the left. When you run the second cell that downloads Meshroom, you should find a folder at `/content/meshroom` that contains everything I was talking about. Let me know if you still can't find it.

**Comment by RayzedByRobots** [comment]
@ab3d-studio - Hey thanks for your reply. I found the featurematching file where you mentioned it. When I double click on featurematching I get what looks like machine code? I was thinking when I opened this file I would be able to find the specific --describerPreset normal argument and change normal to high, save it, and then just run everything as usual. Is this not how it works? Thanks

**Comment by abnlsn** [comment]
Hi! I've been trying to make this work for a little while now. I am not sure quite how to do it yet. I will let you know when I make more progress.

**Comment by RayzedByRobots** [comment]
Hey @AB3-Dev, I know this is getting like a root canal but here's what I've found: 

I preface this with...you'll be able to make more sense out of the following than and ye... 

Good article on using command line and meshroom:
http://filmicworlds.com/blog/command-line-photogrammetry-with-alicevision/

This is a referenced zip in the above article...I opened this up in pycharm and found the FeatureExtraction part where you could change the "normal" to "high" settings. 
http://filmicworlds.com/downloads/2018_08_10_alicevision/run_alicevision.zip

This looks like the file that can change the default settings, but I don't know how it fits in with Donmahallem's Notebook - I don't see run_alicevision file anywhere in the notebook...

That is what I have found. 

Thanks for looking into this. I and others will find this info valuable. 

Ron

**Comment by RayzedByRobots** [comment]
Here is a useful wiki for meshroom on colab. 

https://github.com/alicevision/meshroom/wiki/Meshroom-in-Google-Colab-(cloud)
